In [2]:
import numpy as np

import pandas as pd


In [3]:
data=pd.read_csv("/content/market_data (1).csv")

In [4]:
data.head()

,youtube,facebook,newspaper,sales
0,84.72,19.20,48.96,12.60
1,351.48,33.96,51.84,25.68
2,135.48,20.88,46.32,14.28
3,116.64,1.80,36.00,11.52
4,318.72,24.00,0.36,20.88


In [5]:
y=data["sales"]

In [6]:
y

,sales
0,12.60
1,25.68
2,14.28
3,11.52
4,20.88
...,...
166,9.12
167,11.64
168,15.36
169,30.60


In [13]:
after=data.drop('sales',axis=1).to_numpy()

In [15]:
after.shape

(171, 3)

In [18]:
x1,x2,x3=data["youtube"],data["facebook"],data["newspaper"]

In [22]:
n=len(x1)
x_baias=np.ones((n,1))

In [26]:
final=np.append(x_baias,after,axis=1)

In [27]:
final

array([[  1.  ,  84.72,  19.2 ,  48.96],
       [  1.  , 351.48,  33.96,  51.84],
       [  1.  , 135.48,  20.88,  46.32],
       [  1.  , 116.64,   1.8 ,  36.  ],
       [  1.  , 318.72,  24.  ,   0.36],
       [  1.  , 114.84,   1.68,   8.88],
       [  1.  , 348.84,   4.92,  10.2 ],
       [  1.  , 320.28,  52.56,   6.  ],
       [  1.  ,  89.64,  59.28,  54.84],
       [  1.  ,  51.72,  32.04,  42.12],
       [  1.  , 273.6 ,  45.24,  38.4 ],
       [  1.  , 243.  ,  26.76,  37.92],
       [  1.  , 212.4 ,  40.08,  46.44],
       [  1.  , 352.32,  33.24,   2.16],
       [  1.  , 248.28,  10.08,  31.68],
       [  1.  ,  30.12,  30.84,  51.96],
       [  1.  , 210.12,  27.  ,  37.8 ],
       [  1.  , 107.64,  11.88,  42.84],
       [  1.  , 287.88,  49.8 ,  22.2 ],
       [  1.  , 272.64,  18.96,  59.88],
       [  1.  ,  80.28,  14.04,  44.16],
       [  1.  , 239.76,   3.72,  41.52],
       [  1.  , 120.48,  11.52,   4.32],
       [  1.  , 259.68,  50.04,  47.52],
       [  1.  , 

(X*X(T))-1*(X(t)*y

In [34]:
x_transpose=np.transpose(final)

In [35]:
x_transpose

array([[  1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  , 

In [36]:
first_op=(x_transpose@final) #first operand (xT*x)

array([[1.71000000e+02, 3.04416000e+04, 4.73184000e+03, 6.02604000e+03],
       [3.04416000e+04, 7.20355208e+06, 8.69366232e+05, 1.12080054e+06],
       [4.73184000e+03, 8.69366232e+05, 1.85489568e+05, 1.89002506e+05],
       [6.02604000e+03, 1.12080054e+06, 1.89002506e+05, 3.17784053e+05]])

In [40]:
first_op=np.linalg.inv(first_op)

In [41]:
first_op

array([[ 3.95364413e-02, -8.83018573e-05, -3.75982708e-04,
        -2.14666950e-04],
       [-8.83018573e-05,  5.69244048e-07, -1.92501263e-07,
        -2.18750098e-07],
       [-3.75982708e-04, -1.92501263e-07,  2.01231733e-05,
        -4.15970472e-06],
       [-2.14666950e-04, -2.18750098e-07, -4.15970472e-06,
         1.04629589e-05]])

In [42]:
second_op=x_transpose@y

In [43]:
second_op

array([  2893.8   , 601163.3664,  91670.0544, 108794.0448])

In [49]:
newTheta=first_op.dot(second_op)   #xt*x-1 * xt*y    newTheta

In [48]:

def simpleNormalEquation(theta1,theta2,theta3,yt,fb,nb,theta0):
  line=theta1*yt+theta2*fb+theta3*nb+theta0
  print(line)


In [52]:
simpleNormalEquation(newTheta[1],newTheta[2],newTheta[3],84,19,48,newTheta[0])

11.090622617161099
